name: main
on: [push, pull_request]
jobs:
  test_runner:
    name: CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: add router
        run: |
          sudo add-apt-repository -y ppa:qpid/testing
          sudo apt-get update --allow-unauthenticated
          sudo apt --assume-yes install qdrouterd --allow-unauthenticated
      - name: mysql setup
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SELECT @@VERSION"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "create database skupper;"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "use skupper database;"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "CREATE TABLE greetings (ID int, text varchar(255) );"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "INSERT INTO greetings VALUES (1,'Hello');"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "CREATE USER skupper@localhost IDENTIFIED BY 'reppuks';"
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "GRANT SELECT  ON skupper.* TO 'skupper'@'localhost';"
      - uses: actions/setup-python@v2
      - uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.21.1'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p "$HOME/.local/bin"
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: curl -fL https://github.com/skupperproject/skupper/releases/download/0.6.0/skupper-cli-0.6.0-linux-amd64.tgz | tar -C "$HOME/.local/bin" -xzf -
      - run: ./plano test

