name: main
on: [push, pull_request]
jobs:
  test_runner:
    name: CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: add router
        run: |
          sudo add-apt-repository -y ppa:qpid/testing
          sudo apt-get update --allow-unauthenticated
          sudo apt --assume-yes install qdrouterd --allow-unauthenticated
      - name: mysql version
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SELECT @@VERSION"
